# -*- coding: utf-8 -*-
"""Assignment 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdwkvtfLlG_lcGAod7R_ieSk6UjwhDiK

**Basic Function Coding Questions**

**1. To find the square of a number**
"""

def square(n):
    return n * n

print(square(5))

"""**2. Maximum of two numbers**"""

def maximum(a, b):
    return a if a > b else b

print(maximum(10, 20))

"""**Check if a Number is Prime**"""

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

print(is_prime(7))

"""**4. Calculate factorial of a number**"""

def factorial(n):
    f = 1
    for i in range(1, n + 1):
        f *= i
    return f

print(factorial(5))

"""**5. Reverse a string**"""

def reverse_string(s):
    return s[::-1]

print(reverse_string("Python"))

"""**POSITIONAL & KEYWORD ARGUMENTS**

**6. Sum using positional arguments**
"""

def add(a, b):
    return a + b

print(add(10, 15))

"""**7. Name and age using keyword arguments**"""

def show(name, age):
    print(name, age)

show(age=21, name="Alex")

"""**8. Wrong order gives different output**"""

def subtract(a, b):
    return a - b

print(subtract(10, 5))
print(subtract(5, 10))

"""**9. Area of rectangle using keyword arguments**"""

def area(length, width):
    return length * width

print(area(width=4, length=6))

"""**DEFAULT ARGUMENTS**

**10. Simple interest (default rate = 5%)**
"""

def simple_interest(p, t, r=5):
    return (p * t * r) / 100

print(simple_interest(1000, 2))

"""**11. Power with of a number (default exponent = 2)**"""

def power(a, b=2):
    return a ** b

print(power(5))
print(power(5, 3))

"""**12. Append an element to a list using a default parameter**"""

def add_item(item, lst=None):
    if lst is None:
        lst = []
    lst.append(item)
    return lst

print(add_item(10))
print(add_item(20))

"""**13. Demonstrates the issue with mutable default arguments**"""

def add_item(item, lst=[]):
    lst.append(item)
    return lst

print(add_item(10))
print(add_item(20))

"""*args (Variable-Length Positional Arguments)

**14. Accepts any number of integers and returns their sum**
"""

def total(*args):
    return sum(args)

print(total(1, 2, 3, 4))

"""**15. Accepts any number of numbers and returns the maximum**"""

def max_value(*args):
    return max(args)

print(max_value(10, 5, 25, 15))

"""**16. Multiplies all numbers passed using** *args"""

def multiply(*args):
    result = 1
    for i in args:
        result *= i
    return result

print(multiply(2, 3, 4))

"""**17. Counts how many arguments were passed**"""

def count_args(*args):
    return len(args)

print(count_args(10, 20, 30, 40))

"""**kwargs (Variable-Length Keyword Arguments)

**18. prints all key–value pairs passed using** **kwargs
"""

def show_pairs(**data):
    for k, v in data.items():
        print(k, ":", v)

show_pairs(name="Alex", age=20, city="Delhi")

"""**19. Accepts student details and prints them neatly**"""

def student_details(**details):
    for k, v in details.items():
        print(k, ":", v)

student_details(name="Ravi", roll=101, course="Python")

"""**20. Calculates total marks using values from** **kwargs"""

def total_marks(**marks):
    return sum(marks.values())

print(total_marks(math=80, science=75, english=85))

"""**Positional-Only Arguments**

**21. Accept two numbers as positional-only arguments and returns their difference**
"""

def difference(a, b, /):
    return a - b

print(difference(20, 5))

"""**22. Calculates division using positional-only arguments**"""

def divide(a, b, /):
    return a / b

print(divide(20, 4))

"""**Keyword-Only Arguments**

**23. Operation as keyword-only argument**
"""

def calculate(a, b, *, operation):
    if operation == "add":
        return a + b
    elif operation == "sub":
        return a - b

print(calculate(10, 5, operation="add"))
print(calculate(10, 5, operation="sub"))

"""**24. Salary with keyword-only bonus**"""

def salary(basic, *, bonus):
    return basic + bonus

print(salary(30000, bonus=5000))

"""**Mixed Argument Types**

**25. Accepts: one positional argument, one default argument,**
*args, **kwargs **and prints everything.**
"""

def demo(a, b=10, *args, **kwargs):
    print("Positional:", a)
    print("Default:", b)
    print("*args:", args)
    print("**kwargs:", kwargs)

demo(5, 20, 30, 40, name="Alex", city="Delhi")

"""**26. User activity log using mixed arguments**"""

def log_activity(user, action="login", *devices, **info):
    print("User:", user)
    print("Action:", action)
    print("Devices:", devices)
    print("Info:", info)

log_activity("Ravi", "logout", "mobile", "laptop", ip="192.168.1.1")

"""**Lambda (One-Line Function)**

**27. Add two numbers**
"""

add = lambda a, b: a + b
print(add(10, 20))

"""**28. Check if a number is even**"""

even = lambda n: n % 2 == 0
print(even(8))
print(even(7))

"""**29. Square of each element in a list**"""

nums = [1, 2, 3, 4]
print(list(map(lambda x: x*x, nums)))

"""**30. Convert list to uppercase using map()**"""

names = ["python", "java", "c"]
print(list(map(lambda x: x.upper(), names)))

"""**31. Get odd numbers using filter()**"""

nums = [1, 2, 3, 4, 5]
print(list(filter(lambda x: x % 2 != 0, nums)))

"""**32. Sort tuples by second element using sorted()**"""

t = [(1, 3), (2, 1), (4, 2)]
print(sorted(t, key=lambda x: x[1]))

"""**33. Maximum of two numbers**"""

max_num = lambda a, b: a if a > b else b
print(max_num(15, 25))